version: '3.8'
services:
  backend:
    build: ./backend
    command: python3 project/main.py  # --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      PORT: 5000
    ports:
      - 5000:5000
    volumes:
      - ./backend:/home/backend/project
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.18
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
      MONGODB_APPLICATION_DATABASE: 
    ports:
      - 27017:27017
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:localhost@mongo:27017/