version: '3.8'
services:
  backend:
    build: ./backend
    command: python3 project/main.py  # --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 5000:5000
    volumes:
      - ./backend:/home/backend/project